name: values
description: A Codec implementation that serializes and deserializes key-value pairs with an = separator.
version: 1.0.0
homepage: https://github.com/hacker1024/values.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.10
